Mandarin/courses/urls.py
from django.urls import path

from . import views
from .views import (
    SubjectDetailView,
    CourseDetailView,
    CoursesListView,
    TutorsListView,
    TutorDetailView,
    StudentDetailView,
    CoursesListViewFilter
)

urlpatterns = [
    path('', views.home, name='home'),
    path('subject/<int:pk>/', CoursesListViewFilter.as_view(), name='subject_detail'),
    path('course/<int:pk>/', CourseDetailView.as_view(), name='course_detail'),
    path('courses/', CoursesListView.as_view(), name='courses_list'),
    path('courses/subject_<int:pk>/', CoursesListViewFilter.as_view(), name='courses_list_filter'),
    path('tutors/', TutorsListView.as_view(), name='tutors_list'),
    path('teacher/<int:pk>/', TutorDetailView.as_view(), name='teacher_detail'),
    path('student/<int:pk>/', StudentDetailView.as_view(), name='student_detail'),
    path('addCommentToTeacher/<int:pk>/', views.addCommentToTeacher, name='addCommentToTeacher'),
    path('addCommentToCourse/<int:pk>/', views.addCommentToCourse, name='addCommentToCourse'),
    path('applyForCourseNotRegistered/<int:pk>/', views.applyForCourseNotRegistered, name='applyForCourseNotRegistered'),
    path('applicationFromHome/', views.applyFromHome, name='applyFromHome'),
    path('applyForCourse/<int:pk>/', views.applyForCourse, name='applyForCourse'),
    path('unenrollFromCourse/<int:pk>/', views.unenrollFromCourse, name='unenrollFromCourse')
]

Mandarin/mandarin/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from users.views import SignUpView

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('courses.urls')),
    path('', include('users.urls')),
    path('', include('other_content.urls')),
    path('admin/', admin.site.urls),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signup/student', user_views.register_student, name='student_register'),
    path('signup/teacher', user_views.register_teacher, name='teacher_register'),
    path('profile/', user_views.profile, name='profile'),
    path('update_profile/', user_views.update_profile, name='update_profile'),
    path('payments/', user_views.payments, name='payments'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]
urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Mandarin/users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('make_order/', views.make_order, name='make_order')
]

Mandarin/courses/models.py
from django.db import models
from users.models import Student,Teacher
from django.db.models import Avg, Count
from PIL import Image


class Subject(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='subjects/')

    def __str__(self):
        return self.name

class HomeSubject(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    position = models.IntegerField(default=1, null=True, blank=True)

    def __str__(self):
        return str(self.position)


class Course(models.Model):
    name = models.CharField(max_length=200)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    short_description = models.TextField(max_length=500)
    long_description = models.TextField(null=True, blank=True)
    individual = "Individual"
    group = "Group"
    both = "Individual/Group"
    ROOM_TYPES = (
        (individual, "Individual"),
        (group, "Group"),
        (both, "Individual/Group"),
    )
    room_type = models.CharField(max_length=25,
                             choices=ROOM_TYPES,
                             default="Individual")

    capacity = models.IntegerField(default=1)
    topics = models.TextField()
    video_link = models.CharField(max_length=300, null=True, blank=True)
    price_individual = models.FloatField(null=True, blank=True, default=15)
    price_group = models.FloatField(null=True, blank=True, default=10)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='courses/')
    min_age_individual = models.IntegerField(null=True, blank=True)
    max_age_individual = models.IntegerField(null=True, blank=True)
    min_age_group = models.IntegerField(null=True, blank=True)
    max_age_group = models.IntegerField(null=True, blank=True)
    duration_individual = models.CharField(null=True, blank=True, max_length=300)
    duration_group = models.CharField(null=True, blank=True, max_length=300)
    class_per_week_individual = models.IntegerField(null=True, blank=True, default=1)
    class_per_week_group = models.IntegerField(null=True, blank=True, default=1)

    def __str__(self):
        return self.name

    @property
    def avg_rate(self):
        return CourseComment.objects.filter(course=self).aggregate(Avg('rate'))['rate__avg']

    @property
    def amount_of_comments(self):
        return CourseComment.objects.filter(course=self).count()

    def save(self, *args, **kwargs):
        if self.video_link:
            current_video_link = self.video_link
            video_id = current_video_link
            if "embed" in current_video_link:
                video_id = current_video_link.split('embed/')[1].split(" ")[0][:-1]
            elif "v=" in current_video_link:
                video_id = current_video_link.split('v=')[1].split('&')[0]
            self.video_link = video_id
        super(Course, self).save(*args, **kwargs)


class HomeCourse(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    position = models.IntegerField(default=1, null=True, blank=True)

    def __str__(self):
        return str(self.position)

# class ImageSubject(models.Model):
#     course = models.ForeignKey(Subject, related_name='main_photo', on_delete=models.CASCADE)
#     image = models.ImageField(upload_to='subject_images/')
    #default = models.BooleanField(default=False)
    #different_name.admin_order_field = 'dfname'
    # def save(self):
    #     super().save()
    #
    #     img = Image.open(self.image.path)
    #
    #     if img.height > 420 or img.width > 350:
    #         output_size = (420, 350)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)



# class Teacher(models.Model):
#     first_name = models.CharField(max_length=50)
#     last_name = models.CharField(max_length=50)
#     short_biography = models.TextField(null=True)
#     position = models.CharField(max_length=150, null=True)
#     image = models.ImageField(upload_to='teachers_images/', default='teachers_images/default.png',)
#     rating = models.FloatField(null=True)
#
#     def __str__(self):
#         full_name = self.first_name + ' ' + self.last_name
#         return full_name


    # def save(self):
    #     super().save()
    #
    #     img = Image.open(self.image.path)
    #
    #     if img.height > 420 or img.width > 350:
    #         output_size = (420, 350)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)



# class Course(models.Model):
#     price = models.IntegerField(default=0)
#     teacher = models.ForeignKey(Teacher,on_delete=models.CASCADE)
#     subject = models.ForeignKey(Subject,on_delete=models.CASCADE)
#
#     def __str__(self):
#         text = self.subject.name + ' by ' + str(self.teacher) + ': Price - ' + str(self.price) + '$'
#         return text

class ApplicantNotRegistered(models.Model):
    full_name = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=100, null=True, blank=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    ip = models.CharField(max_length=20, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.full_name

class ApplicationFromHome(models.Model):
    full_name = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=100, null=True, blank=True)
    info_text = models.TextField()
    ip = models.CharField(max_length=20, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.full_name

class CourseParticipant(models.Model):
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    student = models.ForeignKey(Student,on_delete=models.CASCADE)
    ip = models.CharField(max_length=20, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        text = self.student.user.username + ' participation in ' + self.course.subject.name
        return text


class TeacherComment(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    writer = models.ForeignKey(Student, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=350, blank=True)
    rate = models.IntegerField(default=5)
    ip = models.CharField(max_length=20, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        text = self.writer.user.username + ' about ' + self.teacher.user.username
        return text

class CourseComment(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    writer = models.ForeignKey(Student, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=350, blank=True)
    rate = models.IntegerField(blank=True, null=True)
    ip = models.CharField(max_length=20, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        text = self.writer.user.username + ' about ' + self.course.name
        return text

Mandarin/courses/forms.py
from django import forms
from .models import TeacherComment, CourseComment, ApplicantNotRegistered, ApplicationFromHome




class CommentForm(forms.ModelForm):
    class Meta:
        model = TeacherComment
        fields = ['comment_text', 'rate']

class CourseCommentForm(forms.ModelForm):
    class Meta:
        model = CourseComment
        fields = ['comment_text', 'rate']

class TeacherCommentForm(forms.ModelForm):
    class Meta:
        model = TeacherComment
        fields = ['comment_text', 'rate']

class ApplyForCourseForm(forms.ModelForm):
    class Meta:
        model = ApplicantNotRegistered
        fields = ['full_name', 'email', 'phone_number']

class ApplyFromHomeForm(forms.ModelForm):
    class Meta:
        model = ApplicationFromHome
        fields = ['full_name', 'email', 'phone_number', 'info_text']

Mandarin/courses/templates/teachers/teacher_detail.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block content %}
<div class="container py-5">
  <div class="position-relative pb-5">
    {% if user.teacher.id == teacher.id %}
    <button class="btn secondary-button edit-button" type="submit">
      <a href="{% url 'update_profile' %}">Edit profile</a>
    </button>
    {% endif %}
    <div class="row">
      <div class="col-lg-4 col-md-5 col-sm-12">
        <img class="account-img" src="{{ teacher.image.url }}" />
      </div>
      <div class="col-lg-8 col-md-7 col-sm-12 pt-2">
        <h4>{{ teacher.user.get_full_name }}</h4>
        {% if teacher.amount_of_comments > 0 %}
        <div class="rating pb-3">
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star {% if teacher.avg_rate >= 1.5 %} checked {% endif %}"></span>
          <span class="fa fa-star {% if teacher.avg_rate >= 2.5 %} checked {% endif %}"></span>
          <span class="fa fa-star {% if teacher.avg_rate >= 3.5 %} checked {% endif %}"></span>
          <span class="fa fa-star {% if teacher.avg_rate >= 4.5 %} checked {% endif %} "></span>
        </div>
        {% endif %}
        <p class="mb-0"><strong>Bio:</strong> {{teacher.bio}}</p>
        <p><strong>Languages:</strong> {{teacher.languages}}</p>
        <p>{{teacher.description |linebreaks}}</p>
        {% if user.is_student %}
        <a href="#write-review">
          <button class="btn my-2 my-sm-0 main-button mr-4">
            Write a review
          </button></a
        >
        {% endif %}
      </div>
    </div>
  </div>
  <div class="teacher-tabs border-bottom py-5">
    <ul
      class="nav nav-pills justify-content-center"
      id="pills-tab"
      role="tablist"
    >
      <li class="nav-item">
        <a
          class="nav-link active"
          id="pills-courses-tab"
          data-toggle="pill"
          href="#pills-courses"
          role="tab"
          aria-controls="pills-courses"
          aria-selected="true"
          >Courses</a
        >
      </li>
      <li class="nav-item">
        <a
          class="nav-link"
          id="pills-reviews-tab"
          data-toggle="pill"
          href="#pills-reviews"
          role="tab"
          aria-controls="pills-reviews"
          aria-selected="false"
          >Reviews</a
        >
      </li>
      <li class="nav-item">
        <a
          class="nav-link"
          id="pills-videos-tab"
          data-toggle="pill"
          href="#pills-videos"
          role="tab"
          aria-controls="pills-videos"
          aria-selected="false"
          >Videos</a
        >
      </li>
    </ul>
    <div class="tab-content teacher-tabs-content pb-4" id="pills-tabContent">
      <div
        class="tab-pane fade show active"
        id="pills-courses"
        role="tabpanel"
        aria-labelledby="pills-courses-tab"
      >
        <div class="row">
          <h4 class="mx-auto py-4">My Courses</h4>
          <div class="row justify-content-center suggested-courses">
          </div>

		 <div class="owl-carousel course-detail-owl-carousel corses-wrapper mt-0 pt-0">
			{% for course in teacher.course_set.all %}
			<a href="{% url 'course_detail' course.id %}">
			  <div class="card">
				<img
				  class="card-img-top"
				  src="{{course.image.url}}"
				  alt="image"
				/>
				<div class="card-body">
				  <h5 class="card-title">{{course.name}}</h5>
				  <ul>
					{% if course.min_age_individual and course.max_age_individual %}
					  <li>Ages {{course.min_age_individual}}-{{course.max_age_individual}}</li>
					{% elif course.min_age_individual %}
					  <li>Ages {{course.min_age_individual}}+</li>
					{% elif course.max_age_individual %}
					  <li>Ages {{course.max_age_individual}}+</li>
					{% elif course.min_age_group and course.max_age_group %}
					  <li>Ages {{course.min_age_group}}-{{course.max_age_group}}</li>
					{% elif course.min_age_group %}
					  <li>Ages {{course.min_age_group}}+</li>
					{% elif course.max_age_group %}
					  <li>Ages {{course.max_age_group}}+</li>
					{% else %}
					  <li>Ages No limit</li>
					{% endif %}
					<li>Type - {{course.room_type}}</li>
				  </ul>
				  <div class="trainer-info">
					<img
					  class="rounded-circle"
					  alt="tutor"
					  src="{{course.teacher.image.url}}"
					/>
					<div class="trainer-detail">
					  <h6 class="m-0">{{course.teacher.user.get_full_name}}</h6>
					  <p style ="font-size: 12px;">{{course.teacher.bio}}</p>
					</div>
				  </div>
				</div>
			  </div>
			</a>
			 {% endfor %}
		  </div>
        </div>
          {% if teacher.verified == False %}
            <h6>The account is in verification process.</h6>
          {% elif not teacher.course_set.all %}
              There is no course.
          {%endif%}
      </div>

      <div
        class="tab-pane fade"
        id="pills-reviews"
        role="tabpanel"
        aria-labelledby="pills-reviews-tab"
      >
          <h4 class="mx-auto py-4 text-center">My Reviews</h4>
          <div class="review-block">
            {% for comment in comments%}
            <div class="row">
              <div class="col-sm-3">
                <a href="{% url 'student_detail' comment.writer.id %}">
                <img
                  src="{{comment.writer.image.url}}"
                  class="img-rounded"
                />
                  </a>
                <div class="review-block-name"><a href="#">{{comment.writer.user.get_full_name}}</a></div>
                <div class="review-block-date font-italic">
                  {{comment.create_at|date:"M d, Y"}}
                </div>
              </div>
              <div class="col-sm-9">
                <div class="rating">
                  {% if comment.rate %}
                    <div class="rating">
                      <span class="fa fa-star checked"></span>
                      <span class="fa fa-star {% if comment.rate >= 1.5 %} checked {% endif %}"></span>
                      <span class="fa fa-star {% if comment.rate >= 2.5 %} checked {% endif %}"></span>
                      <span class="fa fa-star {% if comment.rate >= 3.5 %} checked {% endif %}"></span>
                      <span class="fa fa-star {% if comment.rate >= 4.5 %} checked {% endif %} "></span>
                    </div>
                    {% endif %}
                </div>
                <div class="review-block-description">
                  {{comment.comment_text}}
                </div>
              </div>
            </div>
              {% empty %}
              <p class="text-center">There is not review yet</p>
            {% endfor %}
          </div>
      </div>
      <div
        class="tab-pane fade"
        id="pills-videos"
        role="tabpanel"
        aria-labelledby="pills-videos-tab"
      >
        <div class="row">
          <h4 class="mx-auto py-4">My Videos</h4>
            {% if course.video_link %}
          <iframe
            width="100%"
            height="auto"
            src="https://www.youtube.com/embed/5vP29nxEZCg"
            title="YouTube video player"
            frameborder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowfullscreen
          >
          </iframe>
            {% endif %}
        </div>
          {% if not course.video_link %}
          <p class="text-center">There is no video</p>
          {% endif %}
      </div>
    </div>
  </div>
  <div class="leave-a-review py-4">
    <h5 class="font-weight-bold">Write Your Review</h5>

    <form
      id="write-review"
      class="review-form"
      action="/addCommentToTeacher/{{teacher.id}}/"
      method="post"
    >
      {% csrf_token %}
      <div class="form-group">
        <div class="input-rating">
          <p>Rate the teacher</p>
          <div class="rating row">
            <div class="rate">
              <input type="radio" id="star5" name="rate" value="5" />
              <label for="star5" title="text">5 stars</label>
              <input type="radio" id="star4" name="rate" value="4" />
              <label for="star4" title="text">4 stars</label>
              <input type="radio" id="star3" name="rate" value="3" />
              <label for="star3" title="text">3 stars</label>
              <input type="radio" id="star2" name="rate" value="2" />
              <label for="star2" title="text">2 stars</label>
              <input type="radio" id="star1" name="rate" value="1" />
              <label for="star1" title="text">1 star</label>
            </div>
          </div>
        </div>
      </div>
      <div class="form-group">
        <textarea
          rows="4"
          name="comment_text"
          class="input"
          placeholder="Type here..."
        ></textarea>
      </div>
      {% if user.id is not None %}
        {% if user.is_teacher %}
        <p>Teachers cannot give reviews.</p>
        {% else %}
        <div class="row button-group mt-4">
          <button class="btn my-2 my-sm-0 secondary-button mr-4">Submit</button>
        </div>
        {% endif %}
      {% else %}
        <p>You must be logged in to post a review.</p>
        <p class="login-reminder">
          Click here to <a href="{% url 'login' %}">login</a> or
          <a href="{% url 'signup' %}">register</a>.
        </p>
      {% endif %}
    </form>
  </div>
</div>
{% endblock content %}

Mandarin/courses/templates/teachers/teachers_list.html
{% extends "base.html" %} {% block content %}
<section class="teachers-list-section">
  <div class="container">
    <div class="row">
      <form
        class="
          form-inline
          mt-4
          search-form-teachers
          ml-lg-auto ml-md-0
          justify-content-center
        "
        id="search"
        method="GET"
        action="{% url 'tutors_list' %}"
      >
        <input
          class="form-control mr-2"
          type="search"
          placeholder="Search teachers..."
          aria-label="Search"
          name="q"
        />
        <button class="btn my-2 my-sm-0 main-button" type="submit">
          Search
        </button>
      </form>
    </div>
    <div class="teacher-list">
      {% for teacher in teachers %}
      <div class="row teacher-list-item">
        <div class="col-lg-4 col-md-5 col-sm-12 col-xs-12">
          <a href="{% url 'teacher_detail' teacher.id %}">
            <img src="{{teacher.image.url}}" alt="teachers picture" />
          </a>
        </div>

        <div class="col-lg-8 col-md-7 col-sm-12 col-xs-12">
          <h3>
            <a href="{% url 'teacher_detail' teacher.id %}"
              >{{teacher.user.get_full_name}}</a
            >
          </h3>
          <p>{{teacher.bio}}</p>
          {% if teacher.amount_of_comments > 0 %}
        <div class="rating pb-3">
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star {% if teacher.avg_rate >= 1.5 %} checked {% endif %}"></span>
          <span class="fa fa-star {% if teacher.avg_rate >= 2.5 %} checked {% endif %}"></span>
          <span class="fa fa-star {% if teacher.avg_rate >= 3.5 %} checked {% endif %}"></span>
          <span class="fa fa-star {% if teacher.avg_rate >= 4.5 %} checked {% endif %} "></span>
        </div>
        {% endif %}
          <div class="m-0 teacher-subjects">
           Subjects:
              {% for teacher_subject_id, subjects_list in teacher_subjects.items %}
                {% if teacher_subject_id == teacher.user.id %}
                  {% for subject in subjects_list %}
                    <a href="{% url 'subject_detail' pk=subject.id %}">{{subject.name}}</a>{% if not forloop.last %}, {% endif %}
                  {% endfor %}
                {% endif %}
              {% endfor %}
          </div>
          <p>Languages: {{teacher.languages}}</p>
        </div>
      </div>

      {% empty %}
        There is no result for the search.
      {% endfor %}
      {% if is_paginated %}
      <div class="row justify-content-end pagination mt-2">
		  <div class="page-links {% if not page_obj.has_previous %} disabled {% endif %}">
			<a
			    class="pr-2"
			    href="{% if page_obj.has_previous %} /tutors?page={{ page_obj.previous_page_number }} {% endif %}"
			    ><i class="fa fa-angle-left" aria-hidden="true"></i
			></a>
		  </div>
		  <div class="page-links">
			  <span class="page-current">
				{{ page_obj.number }}
			  </span>
		  </div>
		<div class="page-links {% if not page_obj.has_next %} disabled {% endif %}">
          <a class="pl-2" href=" {% if page_obj.has_next %} /tutors?page={{ page_obj.next_page_number }}  {% endif %}"
            ><i class="fa fa-angle-right" aria-hidden="true"></i
          ></a>
        </div>
      </div>
      {% endif %}
    </div>
  </div>
</section>

{% endblock content %}