Mandarin/mandarin/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from users.views import SignUpView

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('courses.urls')),
    path('', include('users.urls')),
    path('', include('other_content.urls')),
    path('admin/', admin.site.urls),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signup/student', user_views.register_student, name='student_register'),
    path('signup/teacher', user_views.register_teacher, name='teacher_register'),
    path('profile/', user_views.profile, name='profile'),
    path('update_profile/', user_views.update_profile, name='update_profile'),
    path('payments/', user_views.payments, name='payments'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]
urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Mandarin/users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('make_order/', views.make_order, name='make_order')
]

Mandarin/courses/models.py
from django.db import models
from users.models import Student,Teacher
from django.db.models import Avg, Count
from PIL import Image


class Subject(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='subjects/')

    def __str__(self):
        return self.name

class HomeSubject(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    position = models.IntegerField(default=1, null=True, blank=True)

    def __str__(self):
        return str(self.position)


class Course(models.Model):
    name = models.CharField(max_length=200)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    short_description = models.TextField(max_length=500)
    long_description = models.TextField(null=True, blank=True)
    individual = "Individual"
    group = "Group"
    both = "Individual/Group"
    ROOM_TYPES = (
        (individual, "Individual"),
        (group, "Group"),
        (both, "Individual/Group"),
    )
    room_type = models.CharField(max_length=25,
                             choices=ROOM_TYPES,
                             default="Individual")

    capacity = models.IntegerField(default=1)
    topics = models.TextField()
    video_link = models.CharField(max_length=300, null=True, blank=True)
    price_individual = models.FloatField(null=True, blank=True, default=15)
    price_group = models.FloatField(null=True, blank=True, default=10)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='courses/')
    min_age_individual = models.IntegerField(null=True, blank=True)
    max_age_individual = models.IntegerField(null=True, blank=True)
    min_age_group = models.IntegerField(null=True, blank=True)
    max_age_group = models.IntegerField(null=True, blank=True)
    duration_individual = models.CharField(null=True, blank=True, max_length=300)
    duration_group = models.CharField(null=True, blank=True, max_length=300)
    class_per_week_individual = models.IntegerField(null=True, blank=True, default=1)
    class_per_week_group = models.IntegerField(null=True, blank=True, default=1)

    def __str__(self):
        return self.name

    @property
    def avg_rate(self):
        return CourseComment.objects.filter(course=self).aggregate(Avg('rate'))['rate__avg']

    @property
    def amount_of_comments(self):
        return CourseComment.objects.filter(course=self).count()

    def save(self, *args, **kwargs):
        if self.video_link:
            current_video_link = self.video_link
            video_id = current_video_link
            if "embed" in current_video_link:
                video_id = current_video_link.split('embed/')[1].split(" ")[0][:-1]
            elif "v=" in current_video_link:
                video_id = current_video_link.split('v=')[1].split('&')[0]
            self.video_link = video_id
        super(Course, self).save(*args, **kwargs)


class HomeCourse(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    position = models.IntegerField(default=1, null=True, blank=True)

    def __str__(self):
        return str(self.position)

# class ImageSubject(models.Model):
#     course = models.ForeignKey(Subject, related_name='main_photo', on_delete=models.CASCADE)
#     image = models.ImageField(upload_to='subject_images/')
    #default = models.BooleanField(default=False)
    #different_name.admin_order_field = 'dfname'
    # def save(self):
    #     super().save()
    #
    #     img = Image.open(self.image.path)
    #
    #     if img.height > 420 or img.width > 350:
    #         output_size = (420, 350)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)



# class Teacher(models.Model):
#     first_name = models.CharField(max_length=50)
#     last_name = models.CharField(max_length=50)
#     short_biography = models.TextField(null=True)
#     position = models.CharField(max_length=150, null=True)
#     image = models.ImageField(upload_to='teachers_images/', default='teachers_images/default.png',)
#     rating = models.FloatField(null=True)
#
#     def __str__(self):
#         full_name = self.first_name + ' ' + self.last_name
#         return full_name


    # def save(self):
    #     super().save()
    #
    #     img = Image.open(self.image.path)
    #
    #     if img.height > 420 or img.width > 350:
    #         output_size = (420, 350)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)



# class Course(models.Model):
#     price = models.IntegerField(default=0)
#     teacher = models.ForeignKey(Teacher,on_delete=models.CASCADE)
#     subject = models.ForeignKey(Subject,on_delete=models.CASCADE)
#
#     def __str__(self):
#         text = self.subject.name + ' by ' + str(self.teacher) + ': Price - ' + str(self.price) + '$'
#         return text

class ApplicantNotRegistered(models.Model):
    full_name = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=100, null=True, blank=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    ip = models.CharField(max_length=20, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.full_name

class ApplicationFromHome(models.Model):
    full_name = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=100, null=True, blank=True)
    info_text = models.TextField()
    ip = models.CharField(max_length=20, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.full_name

class CourseParticipant(models.Model):
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    student = models.ForeignKey(Student,on_delete=models.CASCADE)
    ip = models.CharField(max_length=20, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        text = self.student.user.username + ' participation in ' + self.course.subject.name
        return text


class TeacherComment(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    writer = models.ForeignKey(Student, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=350, blank=True)
    rate = models.IntegerField(default=5)
    ip = models.CharField(max_length=20, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        text = self.writer.user.username + ' about ' + self.teacher.user.username
        return text

class CourseComment(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    writer = models.ForeignKey(Student, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=350, blank=True)
    rate = models.IntegerField(blank=True, null=True)
    ip = models.CharField(max_length=20, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        text = self.writer.user.username + ' about ' + self.course.name
        return text

Mandarin/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from PIL import Image, ImageOps
import courses
from django.db.models import Avg
import datetime


class User(AbstractUser):
    is_student = models.BooleanField(default=True)
    is_teacher = models.BooleanField(default=False)
    phone_number = models.CharField(max_length=50, null=True, blank=True)



class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(null=True, blank=True, max_length=300)
    image = models.ImageField(upload_to='student_images/', default='avatar.gif')
    mandarins = models.IntegerField(null=True, default=0)
    description = models.TextField(null=True, blank=True)
    verified = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super(Student, self).save(*args, **kwargs)
        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img = ImageOps.exif_transpose(img)
            img.save(self.image.path)

class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(max_length=300, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='teachers_images/', default='avatar.gif')
    mandarins = models.IntegerField(null=True, default=0)
    verified = models.BooleanField(default=False)
    languages = models.TextField(null=True, blank=True)
    video_link = models.CharField(max_length=300, null=True, blank=True)

    def __str__(self):
        full_name = 'Teacher - ' + self.user.username
        return full_name

    @property
    def avg_rate(self):
        return courses.models.TeacherComment.objects.filter(teacher=self).aggregate(Avg('rate'))['rate__avg']

    @property
    def amount_of_comments(self):
        return courses.models.TeacherComment.objects.filter(teacher=self).count()

    def save(self, *args, **kwargs):
        current_video_link = self.video_link
        video_id = current_video_link
        if current_video_link:
            if "embed" in current_video_link:
                video_id = current_video_link.split('embed/')[1].split(" ")[0][:-1]
            elif "v=" in current_video_link:
                video_id = current_video_link.split('v=')[1].split('&')[0]
        self.video_link = video_id
        super(Teacher, self).save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img  = ImageOps.exif_transpose(img)
            img.save(self.image.path)


def year_choices():
    return [(r,r) for r in range(2021, datetime.date.today().year+1)]

def current_year():
    return datetime.date.today().year

def deadline_day():
    return datetime.date.today() + datetime.timedelta(days=20)


class Payment(models.Model):
    JAN = "January"
    FEB = "February"
    MAR = "March"
    APR = "April"
    MAY = "May"
    JUN = "June"
    JUL = "Jule"
    AUG = "August"
    SEP = "September"
    OCT = "October"
    NOV = "November"
    DEC = "December"

    MONTH_CHOICES = (
        (JAN, "January"),
        (FEB, "February"),
        (MAR, "March"),
        (APR, "APRIL"),
        (MAY, "MAY"),
        (JUN, "JUNE"),
        (JUL, "JULE"),
        (AUG, "August"),
        (SEP, "September"),
        (OCT, "October"),
        (NOV, "November"),
        (DEC, "December")
    )

    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    amount = models.IntegerField(null=True, default=0)
    month = models.CharField(max_length=9, choices=MONTH_CHOICES,default="January")
    year = models.IntegerField(choices=year_choices(), default=current_year())
    is_deadline = models.BooleanField(default=True)
    deadline = models.DateField(default=deadline_day())
    is_paid = models.BooleanField(default=False)
    amount_of_lessons = models.IntegerField(default=1)
    canceled_lessons = models.IntegerField(default=0)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        if self.year:
            text_to_be_returned = self.student.user.username + ' - ' + self.month + ' of ' + str(self.year)
        else:
            text_to_be_returned = 'empty'
        return text_to_be_returned


class Order(models.Model):
    payment = models.ForeignKey(Payment, on_delete=models.CASCADE)
    itf_order_id = models.IntegerField(null=True, blank=True)
    last_massage = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=20, null=True, blank=True)

    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        if self.payment.id:
          text_to_be_returned = self.payment.student.user.username + ' - ' + str(self.payment.id)
        else:
            text_to_be_returned = "Empty"
        return text_to_be_returned

Mandarin/users/forms.py
from django import forms
from .models import User, Student, Teacher
from django.contrib.auth.forms import UserCreationForm


class StudentRegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username','first_name','last_name', 'email', 'phone_number', 'password1', 'password2']
        help_texts = {
            'username': None
        }

    def __init__(self, *args, **kwargs):
        super(StudentRegisterForm, self).__init__(*args, **kwargs)
        self.fields['phone_number'].required = True

    def save(self):
        user = super().save(commit=False)
        user.is_student = True
        user.is_teacher = False
        user.save()
        return user


class TeacherRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'phone_number', 'password1', 'password2']

        help_texts = {
            'username': None
        }

    def __init__(self, *args, **kwargs):
        super(TeacherRegisterForm, self).__init__(*args, **kwargs)
        self.fields['phone_number'].required = True

    def save(self):
        user = super().save(commit=False)
        user.is_student = False
        user.is_teacher = True
        user.save()
        return user


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    first_name = forms.CheckboxInput()


    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'phone_number']
        help_texts = {
            'username': None
        }

    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        self.fields['phone_number'].required = True




class StudentUpdateForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['bio','description','image']
        widgets = {
            'bio': forms.TextInput(attrs={'placeholder': 'Short about yourself'}),
            'description': forms.Textarea(attrs={'placeholder': 'Please describe yourself'}),
        }

    def __init__(self, *args, **kwargs):
        super(StudentUpdateForm, self).__init__(*args, **kwargs)
        self.fields['bio'].required = False
        self.fields['description'].required = False

class TeacherUpdateForm(forms.ModelForm):

    class Meta:
        model = Teacher
        fields = ['bio','description','video_link','languages','image']
        widgets = {
            'bio': forms.TextInput(attrs={'placeholder': 'Short about yourself'}),
            'description': forms.Textarea(attrs={'placeholder': 'Please describe yourself'}),
            'languages': forms.TextInput(attrs={'placeholder': 'e.g. Armenian, English, Russian'}),
        }

    def __init__(self, *args, **kwargs):
        super(TeacherUpdateForm, self).__init__(*args, **kwargs)
        self.fields['bio'].required = False
        self.fields['description'].required = False
        self.fields['video_link'].required = False

Mandarin/users/templates/users/login.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="content-section login-form my-5 p-4">
      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="font-weight-bold text-md-center">Welcome back!</legend>
          <p class="text-md-center">Enter your credetials to login</p>
          {{ form|crispy }}
        </fieldset>
        <div class="form-group">
          <button class="btn secondary-button" type="submit">Login</button>
        </div>
      </form>
      <div class="pt-3">
        <small class="text-muted login-reminder">
          New to Mandarin? <a class="ml-2" href="{% url 'signup' %}">Sign up</a>
        </small>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

Mandarin/users/templates/users/logout.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h2>You have been logged out</h2>
            <div class="border-top pt-3">
                <small class="text-muted">
                    <a href="{% url 'login' %}">Log In Again</a>
                </small>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

Mandarin/users/templates/users/payments.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block content %}
<div class="container py-5">
	{% if payment_status == "confirmed" %}
	<div class="alert alert-success alert-dismissible fade show" role="alert">
	  Payment was successfully processed.
	  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
	  </button>
	</div>
	{% elif payment_status == "error" %}
	<div class="alert alert-danger alert-dismissible fade show" role="alert">
	  There was an error. Please try again or contact customer service.
	  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
	  </button>
	</div>
	{% endif %}

	<div class='payment-info'>
		<div class='payment-table'>
			<h4 class="text-center py-4">My Payments</h4>
			
			  {% for payment in not_paid_payment %}
			  
			<div class="table-responsive-md">
			<table class="table">
			  <thead class="thead-light">
				<tr>
				  <th scope="col">Amount (USD)</th>
					<th scope="col">In AMD</th>
				  <th scope="col">Period</th>
				  <th scope="col">Status</th>
				  <th scope="col">Deadline</th>
				  <th scope="col">Action</th>
				</tr>
			  </thead>
			  <tbody>
				<tr>
				  <td>${{payment.amount}}</td>
					<td>{% widthratio payment.amount 1 490 %} ֏</td>
				  <td>{{payment.month}} of {{payment.year}} </td>
				  <td>{% if payment.is_paid %}
						Paid
					  {% else %}
						Awaiting
					  {% endif %}
				  </td>
					{% if payment.is_deadline %}
				  <td>{{payment.deadline}}</td>
					{% endif %}
				  <td>
				  {% if not payment.is_paid %}
					<button class="btn secondary-button" type="submit">
					  <a href="{% url 'make_order' %}">Pay Online</a>
					</button>
				  {% endif %}
				  </td>
				</tr>
			  </tbody>
			</table>
			</div>
			{% empty %}
			  <div class="container text-center">
				<p>
					You don't have any awaiting invoices.
				</p>
				<a href="{% url 'courses_list' %}">
				  <button type="button" class="btn btn-see-all main-button">
				  See All Courses
				  </button>
				</a>
			  </div>
			{% endfor %}
		</div>
		<div class='payment-history-table'>
			<h4 class="text-center py-4">Payment History</h4>

			{% if payments_list %}
			<div class="table-responsive-md">
			<table class="table">
			  <thead class="thead-light">
				<tr>
				  <th scope="col">Amount</th>
				  <th scope="col">Period</th>
				  <th scope="col">Status</th>
				</tr>
			  </thead>
				{% for payment in payments_list %}
			  <tbody>
				<tr>
				  <td>${{payment.amount}}</td>
				  <td>{{payment.month}} of {{payment.year}}</td>
				  <td>{% if payment.is_paid %}
						Paid
					  {% else %}
						Awaiting
					  {% endif %}</td>
				</tr>
			  </tbody>
				{% endfor %}
			</table>
			</div>
			 <div class="row justify-content-end pagination">
			  <div class="page-links {% if not page_obj.has_next %} disabled {% endif %}">
				<a class="pr-2" href="#"
				  ><i class="fa fa-angle-left" aria-hidden="true"></i
				></a>
			  </div>
			  <div class="page-links">
				<span class="page-current">
				  1
				</span>
			  </div>
			  <div class="page-links {% if not page_obj.has_next %} disabled {% endif %}">
				<a class="pl-2" href="#"
				  ><i class="fa fa-angle-right" aria-hidden="true"></i
				></a>
			  </div>
			</div>
			{% else %}
			  <div class="container text-center">
				<p>
					You don't have payment history.
				</p>
				<a href="{% url 'courses_list' %}">
				  <button type="button" class="btn btn-see-all main-button">
				  See All Subjects
				  </button>
				</a>
			  </div>
			{% endif %}

		</div>
	</div>
	
	<!--
	<div class="alert alert-success alert-dismissible fade show" role="alert">
	  Payment was successfully processed.
	  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
	  </button>
	</div>
	-->
	 
  {% endblock content %}
</div>

Mandarin/users/templates/users/profile_student.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block content %}
<div class="container py-5">
  <div class="position-relative border-bottom pb-5">
    <div class="row">
      <div class="col-lg-4 col-md-5 col-sm-12">
        <img class="account-img" src="{{ user.student.image.url }}" />
      </div>
      <div class="col-lg-5 col-md-5 col-sm-12 pt-2">
        <h4> {{ user.get_full_name }} </h4>

        {% if user.student.bio %}
          <p><strong>{{user.student.bio}}</strong> </p>
        {% else %}
          <p class="edit-link">Bio: <a href="{% url 'update_profile' %}">Please fill</a></p>
        {% endif %}
        <p>{{user.student.description |linebreaks}}</p>
      </div>
	   <div class="col-lg-3 col-md-2 col-sm-12">
		<button class="btn main-button mb-1" type="submit">
		  <a href="{% url 'payments' %}">My Payments</a>
		</button>
	    <button class="btn secondary-button" type="submit">
		  <a href="{% url 'update_profile' %}"> Edit profile </a>
		</button>
	  </div>
    </div>
  </div>
  <div class="container">
    <h4 class="text-center py-4">My Courses</h4>
    <div class="row justify-content-center suggested-courses">
        {% for student_course in user.student.courseparticipant_set.all %}
        <div class="card col-lg-3 col-md-6 col-sm-6 col-xs-12 border-0">
          <div class="class-item">
            <a href="{% url 'course_detail' student_course.course.id %}">
              <img
                class="card-img-top"
                src="{{student_course.course.image.url}}"
                alt="Card image cap"
              />
              <div class="card-body">
                <h5 class="card-title">{{student_course.course.name}}</h5>
                <ul>
                  {% if student_course.course.min_age and student_course.course.max_age %}
                  <li>Ages {{student_course.course.min_age}}-{{student_course.course.max_age}}</li>
                  {% elif student_course.course.min_age %}
                  <li>Ages {{student_course.course.min_age}}+</li>
                  {% elif student_course.course.max_age %}
                  <li>Ages {{student_course.course.max_age}}+</li>
                  {% else %}
                  <li>Ages No limit</li>
                  {% endif %}
                  <li>Type - {{student_course.course.room_type}}</li>
                </ul>
                <div class="trainer-info">
                  <img
                    class="rounded-circle"
                    alt="tutor picture"
                    src="{{student_course.course.teacher.image.url}}"
                  />
                  <div class="trainer-detail">
                    <h5 class="m-0">{{student_course.course.teacher.user.get_full_name}}</h5>
                    <p class="font-italic">{{student_course.course.teacher.bio}}</p>
                  </div>
                </div>
              </div>
            </a>
          </div>
        </div>
      {% empty %}
      You have not registered for any course.
      <div class="container text-center">
        <p>

        </p>
        <a href="{% url 'courses_list' %}">
          <button type="button" class="btn btn-see-all main-button">
          See All Courses
          </button>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
  {% endblock content %}
</div>

Mandarin/users/templates/users/profile_student_old.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block content %}
<button class="btn secondary-button" type="submit">
      <a href="{% url 'payments' %}">My Payments</a>
    </button>
<div class="container py-5">
  <div class="position-relative border-bottom pb-5">
    <button class="btn secondary-button edit-button" type="submit">
      <a href="{% url 'update_profile' %}">Edit profile</a>
    </button>
    <div class="row">
      <div class="col-lg-4 col-md-5 col-sm-12">
        <img class="account-img" src="{{ user.student.image.url }}" />
      </div>
      <div class="col-lg-8 col-md-7 col-sm-12 pt-2">
        <h4> {{ user.get_full_name }} </h4>

        {% if user.student.bio %}
          <p><strong>{{user.student.bio}}</strong> </p>
        {% else %}
          <p class="edit-link">Bio: <a href="{% url 'update_profile' %}">Please fill</a></p>
        {% endif %}
        <p>{{user.student.description |linebreaks}}</p>
      </div>
    </div>
  </div>
  <div class="container">
    <h4 class="text-center py-4">My Courses</h4>
    <div class="row justify-content-center suggested-courses">
        {% for student_course in user.student.courseparticipant_set.all %}
        <div class="card col-lg-3 col-md-6 col-sm-6 col-xs-12 border-0">
          <div class="class-item">
            <a href="{% url 'course_detail' student_course.course.id %}">
              <img
                class="card-img-top"
                src="{{student_course.course.image.url}}"
                alt="Card image cap"
              />
              <div class="card-body">
                <h5 class="card-title">{{student_course.course.name}}</h5>
                <ul>
                  {% if student_course.course.min_age and student_course.course.max_age %}
                  <li>Ages {{student_course.course.min_age}}-{{student_course.course.max_age}}</li>
                  {% elif student_course.course.min_age %}
                  <li>Ages {{student_course.course.min_age}}+</li>
                  {% elif student_course.course.max_age %}
                  <li>Ages {{student_course.course.max_age}}+</li>
                  {% else %}
                  <li>Ages No limit</li>
                  {% endif %}
                  <li>Type - {{student_course.course.room_type}}</li>
                </ul>
                <div class="trainer-info">
                  <img
                    class="rounded-circle"
                    alt="tutor picture"
                    src="{{student_course.course.teacher.image.url}}"
                  />
                  <div class="trainer-detail">
                    <h5 class="m-0">{{student_course.course.teacher.user.get_full_name}}</h5>
                    <p class="font-italic">{{student_course.course.teacher.bio}}</p>
                  </div>
                </div>
              </div>
            </a>
          </div>
        </div>
      {% empty %}
      You have not registered for any course.
      <div class="container text-center">
        <p>

        </p>
        <a href="{% url 'courses_list' %}">
          <button type="button" class="btn btn-see-all main-button">
          See All Courses
          </button>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
  {% endblock content %}
</div>

Mandarin/users/templates/users/register.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="content-section signup-form my-5 p-4">
      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="font-weight-bold text-md-center">Join Today</legend>
          <p class="text-md-center">Please sign up using your email</p>
          {{ form|crispy }}
        </fieldset>
        <div class="form-group">
          <button class="btn secondary-button" type="submit">Sign Up</button>
        </div>
      </form>
      <div class="pt-3">
        <small class="text-muted login-reminder">
          Already have an account? <a class="ml-2" href="#">Login</a>
        </small>
      </div>
    </div>
  </div>
</div>
{% endblock content %}